plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '[7.0,7.1)'
    id 'java'
}

group = "com.github.xSasakiHaise"
version = "2.0.1"
archivesBaseName = "hellascontrol"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // NeoForge 1.21.1 requires Java 21
    }
}

minecraft {
    mappings channel: 'official', version: '1.21.1'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    minecraft 'net.neoforged:neoforge:21.1.65'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "hellascontrol"
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}

jar {
    manifest {
        attributes(
                "Specification-Title": "HellasControl",
                "Specification-Vendor": "xSasaki_Haise",
                "Specification-Version": "1",
                "Implementation-Title": "HellasControl",
                "Implementation-Version":"2.0.1",
                "Implementation-Vendor": "xSasaki_Haise"
        )
    }
}
