modLoader="javafml"
loaderVersion="[2,)"
logoFile="HellasControl.png"
license="Restricted"

[[mods]]
modId="hellascontrol"
version="2.0.1"
displayName="HellasControl"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
crafted by the Hephaestus Forge
'''

[[dependencies.hellascontrol]]
modId="neoforge"
mandatory=true
versionRange="[21.1.65,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellascontrol]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellascontrol]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,)"
ordering="AFTER"
side="BOTH"
